[package]
name = "vulkano-bufferless"
version = "0.1.0"
authors = ["Richard M. <richard.meester@gmail.com>"]
publish = false

[dependencies]
vulkano = "0.11"
vulkano-shaders = "0.11"
vulkano-win = "0.11"
cgmath = "0.16"
image = "0.20"
winit = "0.18"
time = "0.1.40"
